//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadFollowUp
    {
        public int LeadFollowUpId { get; set; }
        public int LeadId { get; set; }
        public int LeadDetailId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpComment { get; set; }
        public string FollowUpStauts { get; set; }
    }
}
