//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadAssign
    {
        public int LeadId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime LeadDate { get; set; }
        public int LeadCategoryId { get; set; }
        public string LeadDetail { get; set; }
        public string Attachment { get; set; }
        public string FileType { get; set; }
        public string Instruction { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual LeadCategory LeadCategory { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
