//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadDetail
    {
        public int LeadDetailId { get; set; }
        public string LeadName { get; set; }
        public string LeadMobileNo { get; set; }
        public string LeadComment { get; set; }
        public int LeadId { get; set; }
        public Nullable<byte> LeadStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
    
        public virtual LeadAssign LeadAssign { get; set; }
    }
}
