//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveRequest()
        {
            this.LeaveDetails = new HashSet<LeaveDetail>();
        }
    
        public int LeaveId { get; set; }
        public int StaffId { get; set; }
        public byte LeaveType { get; set; }
        public System.DateTime LeaveDateTo { get; set; }
        public System.DateTime LeaveDateFrom { get; set; }
        public int NoOfDays { get; set; }
        public string Message { get; set; }
        public byte LeaveStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveDetail> LeaveDetails { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
