//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDetail
    {
        public int LeaveDetailsId { get; set; }
        public int LeaveId { get; set; }
        public byte LeaveStatus { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public string Opinion { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        public virtual LeaveRequest LeaveRequest { get; set; }
    }
}
