//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeDetail { get; set; }
        public string Attachments { get; set; }
        public string FileFormat { get; set; }
        public System.DateTime NoticeDate { get; set; }
        public byte NoticeStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdaedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
