//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notic
    {
        public int NoticId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime Noticdate { get; set; }
        public string NoticDetail { get; set; }
        public string Attachments { get; set; }
        public string FileFormate { get; set; }
        public byte NoticStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdaedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
