//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResignationDetail
    {
        public int ResignationDetailId { get; set; }
        public int ResignationId { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime DepatureDate { get; set; }
        public byte ResignationStatus { get; set; }
        public string BreafReason { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public string Instruction { get; set; }
    
        public virtual Resignation Resignation { get; set; }
    }
}
