//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resignation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resignation()
        {
            this.ResignationDetails = new HashSet<ResignationDetail>();
        }
    
        public int ResignationId { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime DepatureDate { get; set; }
        public string Statement { get; set; }
        public string BreafReason { get; set; }
        public byte Resignationstatus { get; set; }
        public string Instruction { get; set; }
        public int StaffId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdaedOn { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResignationDetail> ResignationDetails { get; set; }
    }
}
