//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryManagement
    {
        public int StaffId { get; set; }
        public int SalaryId { get; set; }
        public byte Months { get; set; }
        public string TotalWorkingDay { get; set; }
        public string AbsentDay { get; set; }
        public string WorkingDay { get; set; }
        public byte PaymentMode { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Amount { get; set; }
        public string TransactionNo { get; set; }
        public string Remarks { get; set; }
        public string BasicSalary { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
